### ISSUE TITLE
Timeout feature

### ISSUE THREAD

**Issue by npmccallum** [containers/conmon#162]
I'm looking for a timeout feature for conmon. Specifically, I want conmon to kill the container if it doesn't exit before a timeout period elapses.

Currently, conmon has a [mostly undocumented command line option](https://github.com/containers/conmon/blob/27eb3044c0ec0b7df9e936ab7658f4290ae42f35/src/cli.c#L85) `--timeout`. It is not clear what this feature actually does. But I suspect that it just [exits conmon after a period of time](https://github.com/containers/conmon/blob/27eb3044c0ec0b7df9e936ab7658f4290ae42f35/src/ctr_exit.c#L90). It is not obvious to me that it actually kills the container at the timeout.

I'm not sure why it is useful to exit conmon at a timeout without killing the container. But would conmon consider a patch to kill the container at the timeout (either as the default behavior or behind another CLI option)?

**Comment by haircommander** [comment]
this timeout is used for the a detached exec, where conmon is expected to exit before any of the container logs are accessed. (ref)[https://github.com/cri-o/cri-o/blob/master/internal/oci/runtime_oci.go#L409]

the timeout does kill the container_pid [ref](https://github.com/containers/conmon/blob/27eb3044c0ec0b7df9e936ab7658f4290ae42f35/src/conmon.c#L438), but, again, it's only used for an exec. I suppose it could time out after a create, but it would not be relative to the container start, because conmon runs the create then sits listening on sockets until the container exits.

I'm assuming you want the container to timeout after it *starts*, rather than after it was created (podman run == runc create + runc start). This seems more of podman job to me

**Comment by npmccallum** [comment]
> I'm assuming you want the container to timeout after it _starts_, rather than after it was created (podman run == runc create + runc start). This seems more of podman job to me

Correct. I've opened an issue with podman above.
